# Site settings
author: Kristy Parker
title: Web Development Learning Process
header-img: img/home-bg.png
email: kristyparker1@gmail.com
copyright_name: Kristy Parker
description: > # this means to ignore newlines until "baseurl:"
  The journey of learning web development with Flatiron School.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kristynp

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
